export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const DELIVERY_TERMS = [
  "Standard Shipping",
  "Express / Next-Day Delivery",
  "Customer Pickup / Will Call",
  "Local Delivery",
  "Digital Delivery",
  "No Shipping Required / Service",
  "EXW - Ex Works",
  "FOB - Free on Board",
  "DAP - Delivered at Place",
  "DDP - Delivered Duty Paid",
];

export const PAYMENT_TERMS = [
  "Due on Receipt",
  "Net 7",
  "Net 15",
  "Net 30",
  "Net 45",
  "Net 60",
  "PIA - Payment in Advance",
  "COD - Cash on Delivery",
  "EOM - End of Month",
  "50% Deposit / Balance on Completion",
  "2/10 Net 30",
];
